### PR TITLE
Chat features: include emoticon auto-completion

### PR DESCRIPTION
**Pull request by goldfndr**
*Description of changes:*

Include auto-complete information from https://answers.chime.aws/questions/60/does-amazon-chime-support-emojis.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by goldfndr** [comment]
If auto-completion of emoticons within markdown backticks is considered a bug, this should probably be edited further once the bug is resolved.

**Comment by lkdavies** [comment]
Thank you for your pull request. I've edited it per the AWS style guidelines. I'm happy to merge your pull request after you review the edits.

**Comment by goldfndr** [comment]
I took another look. While the Android client (as of 4.31.6040) doesn't perform emoticon (at least "C:") parsing within a markdown code block, the Windows client (as of 4.30.9449.0, build 1.0.208642.0) and web client (as of today) do. I somehow missed this aspect in the linked announcement.

EDIT: the linked auto-complete information is dated 2016, and the Android client was released on Google Play in 2017.

Until the desktop client issue is resolved, it would be inaccurate to merge your edit. If the desktop client issue is a WONTFIX (i.e. maintain different views on Android vs desktop -or- make Android client identically problematic) then your edit can be merged after one or more minor further edits.

**Comment by lkdavies** [comment]
Hi, 

In Amazon Chime chat, you can send markdown text by placing /md in front of the text. You can send code blocks by placing /code in front of the text. 

The emoticon auto-complete works for the desktop clients and web app when sending regular or markdown (/md) text. Emoticon auto-complete does not work for the desktop clients or web app when sending code blocks (/code). I tested with the Android app and emoticon auto-complete only works in standard texts. I'll propose one more small edit to the text to reflect this.

**Review by ColonelWilco — APPROVED** [review]

**Pull request merged**
